# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('foto', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
