# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170907_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
